In [35]:
import pandas as pd

In [36]:
data = pd.read_csv('data/per.csv', encoding='utf8') # encoding='utf8'-> چون فارسی
data.head()

,NewsID,Title,Body,Date,Time,Category,Category2
0,843656,\nوزير علوم درجمع استادان نمونه: سن بازنشستگي ...,\nوزير علوم در جمع استادان نمونه كشور گفت: از ...,\n138/5//09,\n0:9::18,\nآموزشي-,\nآموزشي
1,837144,\nگردهمايي دانش‌آموختگان موسسه آموزش عالي سوره...,\nبه گزارش سرويس صنفي آموزشي خبرگزاري دانشجويا...,\n138/5//09,\n1:4::11,\nآموزشي-,\nآموزشي
2,436862,\nنتايج آزمون دوره‌هاي فراگير دانشگاه پيام‌نور...,\nنتايج آزمون دوره‌هاي فراگير مقاطع كارشناسي و...,\n138/3//07,\n1:0::03,\nآموزشي-,\nآموزشي
3,227781,\nهمايش يكروزه آسيب شناسي مفهوم روابط عمومي در...,\n,\n138/2//02,\n1:3::42,\nاجتماعي-خانواده-,\nاجتماعي
4,174187,\nوضعيت اقتصادي و ميزان تحصيلات والدين از مهمت...,\nمحمدتقي علوي يزدي، مجري اين طرح پژوهشي در اي...,\n138/1//08,\n1:1::49,\nآموزشي-,\nآموزشي

In [37]:
with open('data/stopwords.txt', encoding='utf8') as stopwords_file:
    stopwords = stopwords_file.readlines()


stopwords = [line.replace('\n', '') for line in stopwords]
stopwords

['!',
 '"',
 '#',
 '$',
 '%',
 '&',
 "'",
 '(',
 ')',
 '*',
 '+',
 ',',
 '-',
 '.',
 '...',
 '....',
 '/',
 ':',
 '<',
 '=',
 '>',
 '@',
 '[',
 '\\',
 ']',
 '^',
 '_',
 '`',
 '{',
 '|',
 '}',
 '~',
 '«',
 '»',
 '،',
 '؛',
 '؟',
 'ء',
 'آاو و و و',
 'آباد',
 'آخ',
 'آخر',
 'آخرها',
 'آخه',
 'آدمهاست',
 'آرام',
 'آرام آرام',
 'آره',
 'آری',
 'آزادانه',
 'آسان',
 'آسانی',
 'آسيب پذيرند',
 'آسیب',
 'آسیب پذیرند',
 'آشكارا',
 'آشنايند',
 'آشنایند',
 'آشکارا',
 'آقا',
 'آقای',
 'آقایان',
 'آمد',
 'آمدن',
 'آمده',
 'آمرانه',
 'آن',
 'آن ها',
 'آن گاه',
 'آنان',
 'آناني',
 'آنانی',
 'آنجا',
 'آنرا',
 'آنطور',
 'آنقدر',
 'آنكه',
 'آنها',
 'آنهاست',
 'آنچنان',
 'آنچنان كه',
 'آنچنان که',
 'آنچه',
 'آنکه',
 'آنگاه',
 'آن\u200cها',
 'آهان',
 'آهاي',
 'آهای',
 'آور',
 'آورد',
 'آوردن',
 'آورده',
 'آوه',
 'آيا',
 'آيد',
 'آی',
 'آیا',
 'آید',
 'آیند',
 'ا',
 'ابدا',
 'ابلهانه',
 'ات',
 'اتفاقا',
 'اثر',
 'اثرِ',
 'اجراست',
 'احتراما',
 'احتمالا',
 'احياناً',
 'احیانا',
 'احیاناً',
 'اخ',
 'اختصارا',
 'اخر',
 'اخرها',
 'اخه',
 'اخيراً',
 'اخیر',
 'اخیرا',
 'اخیراً',
 'اراسته',
 'ارام',
 'ارایه',
 'ارنه',
 'اره',
 'اری',
 'از',
 'از آن پس',
 'از بس که',
 'از جمله',
 'ازادانه',
 'ازان',
 'ازانجا',
 'ازانجاكه',
 'ازاين رو',
 'ازاین',
 'ازاین رو',
 'ازاینرو',
 'ازبه',
 'ازجمله',
 'ازروی',
 'ازسر',
 'ازش',
 'ازقبیل',
 'ازلحاظ',
 'ازنظر',
 'ازو',
 'ازیك',
 'اس',
 'اساس',
 'اساسا',
 'اساساً',
 'اسان',
 'اسانتر',
 'اسانی',
 'است',
 'استفاد',
 'استفاده',
 'اسلامي اند',
 'اسلامی اند',
 'اش',
 'اشان',
 'اشتباها',
 'اشد',
 'اشفته',
 'اشكار',
 'اشكارا',
 'اشكارتر',
 'اشنایند',
 'اشند',
 'اشکارا',
 'اشیم',
 'اصطلاجا',
 'اصطلاحا',
 'اصلا',
 'اصلاً',
 'اصولا',
 'اصولاً',
 'اطلاعند',
 'اعلام',
 'اغلب',
 'افتاد',
 'افتادن',
 'افزود',
 'افسوس',
 'افقی',
 'اقل',
 'اقلا',
 'اقليت',
 'اقلیت',
 'اكتسابا',
 'اكثر',
 'اكثرا',
 'اكثراً',
 'اكثريت',
 'اكثریت',
 'اكنون',
 'الا',
 'الاسف',
 'الان',
 'الایِ',
 'البته',
 'البتّه',
 'الته',
 'التّه',
 'الزاما',
 'الظاهر',
 'المقدور',
 'الهي',
 'الهی',
 'الي',
 'الی',
 'ام',
 'اما',
 'امان',
 'امرانه',
 'امروز',
 'امروزه',
 'امسال',
 'امشب',
 'امور',
 'امورات',
 'اميدوارم',
 'اميدوارند',
 'اميدواريم',
 'امیدوارم',
 'امیدوارند',
 'امیدواریم',
 'ان',
 'ان شاأالله',
 'انان',
 'انانی',
 'انتها',
 'انجام',
 'اند',
 'اندك',
 'اندكي',
 'اندكی',
 'اندکی',
 'انرا',
 'انشاالله',
 'انشالا',
 'انصافا',
 'انطور',
 'انقدر',
 'انكس',
 'انكه',
 'انم',
 'انها',
 'انهاست',
 'انوقت',
 'انچنان',
 'انچه',
 'انکه',
 'انگار',
 'انگاه',
 'انگه',
 'انگونه',
 'اه',
 'اهان',
 'اهای',
 'او',
 'اور',
 'اورد',
 'اوردن',
 'اوست',
 'اول',
 'اولا',
 'اولاً',
 'اولش',
 'اولین',
 'اومد',
 'اومده',
 'اون',
 'اونا',
 'اونایی',
 'اونجا',
 'اونجور',
 'اونجوری',
 'اونجوری که',
 'اونهمه',
 'اوه',
 'اویی',
 'اي',
 'ايشان',
 'ايم',
 'اين',
 'اين جوري',
 'اين قدر',
 'اين گونه',
 'اينان',
 'اينجا',
 'اينجاست',
 'اينكه',
 'اينها',
 'اينهاست',
 'اينو',
 'اکثر',
 'اکثرا',
 'اکثراً',
 'اکثریت',
 'اکنون',
 'اگاهانه',
 'اگر',
 'اگر چه',
 'اگرنه',
 'اگرچه',
 'اگه',
 'ای',
 'ایا',
 'اید',
 'ایشان',
 'ایم',
 'این',
 'این جوری',
 'این دفعه',
 'این قدر',
 'این گونه',
 'اینا',
 'اینان',
 'اینجا',
 'اینجاست',
 'اینجور',
 'اینجوری',
 'ایند',
 'اینرو',
 'اینست',
 'اینطور',
 'اینطوری',
 'اینقدر',
 'اینك',
 'اینكه',
 'اینم',
 'اینه',
 'اینها',
 'اینهاست',
 'اینهمه',
 'اینو',
 'اینچنین',
 'اینک',
 'اینکه',
 'اینگونه',
 'این\u200cها',
 'ب',
 'ب ',
 'با',
 'بااطمینان',
 'باانكه',
 'بااين حال',
 'بااين وجود',
 'بااین',
 'بااین حال',
 'بااین وجود',
 'بااینكه',
 'باتوجه',
 'باد',
 'بار',
 'بارة',
 'باره',
 'بارها',
 'بارهاوبارها',
 'بارهٌ',
 'باز',
 'باز هم',
 'بازاندیشانه',
 'بازم',
 'بازهم',
 'بازي كنان',
 'بازيگوشانه',
 'بازی',
 'بازی کنان',
 'بازیگوشانه',
 'باستثنای',
 'باش',
 'باشد',
 'باشم',
 'باشند',
 'باشه',
 'باشيم',
 'باشی',
 'باشید',
 'باشیم',
 'باعلاقه',
 'بالا',
 'بالاتر',
 'بالاخره',
 'بالاخص',
 'بالاست',
 'بالاي',
 'بالای',
 'بالایِ',
 'بالضرور',
 'بالطبع',
 'بالعكس',
 'بالعکس',
 'بالقوه',
 'بالله',
 'بالنتیجه',
 'بالنسبه',
 'باهم',
 'باوجود',
 'باوجودانكه',
 'باوجوداینكه',
 'باوجودي كه',
 'باوجودی',
 'باوجودی که',
 'باوجودیكه',
 'باورند',
 'بايد',
 'باید',
 'بایستی',
 'ببینم',
 'ببینید',
 'بتازگی',
 'بتدريج',
 'بتدریج',
 'بتمامی',
 'بتوان',
 'بتواند',
 'بتوانی',
 'بتوانیم',
 'بجا',
 'بجای',
 'بجز',
 'بخاطر',
 'بخاطراینكه',
 'بخردانه',
 'بخش',
 'بخشه',
 'بخشی',
 'بخصوص',
 'بخواه',
 'بخواهد',
 'بخواهم',
 'بخواهند',
 'بخواهی',
 'بخواهید',
 'بخواهیم',
 'بخوبي',
 'بخوبی',
 'بد',
 'بد جور',
 'بدان',
 'بدانجا',
 'بدانها',
 'بدانید',
 'بدبینانه',
 'بدجور',
 'بدخواهانه',
 'بدرستی',
 'بدرشتی',
 'بدلخواه',
 'بدم',
 'بده',
 'بدهید',
 'بدون',
 'بدين',
 'بدين ترتيب',
 'بدينجا',
 'بدید',
 'بدیم',
 'بدین',
 'بدین ترتیب',
 'بدینجا',
 'بدینسان',
 'بر',
 'برآن',
 'برآنند',
 'برا',
 'برابر',
 'برابرِ',
 'براثر',
 'براحتی',
 'براساس',
 'براستی',
 'بران',
 'برانند',
 'برانهاست',
 'براي',
 'برايت',
 'برايش',
 'برايشان',
 'برايم',
 'برايمان',
 'برای',
 'برایت',
 'برایش',
 'برایشان',
 'برایم',
 'برایمان',
 'برایِ',
 'برحسب',
 'برخلاف',
 'برخوردار',
 'برخوردارند',
 'برخي',
 'برخی',
 'برداري',
 'برداری',
 'برداشتن',
 'بردن',
 'برروی',
 'برعكس',
 'برعکس',
 'برغم',
 'برم',
 'برمی',
 'برن',
 'برنامه',
 'برنامه سازهاست',
 'برنمی',
 'بره',
 'برو',
 'بروز',
 'بروشني',
 'بروشنی',
 'برپا',
 'بری',
 'برید',
 'بریزید',
 'بریم',
 'بزرگ',
 'بزعم',
 'بزنید',
 'بزودی',
 'بس',
 'بسا',
 'بسادگي',
 'بسادگی',
 'بسته',
 'بسختي',
 'بسختی',
 'بسرعت',
 'بسهولت',
 'بسوي',
 'بسوی',
 'بسي',
 'بسيار',
 'بسياري',
 'بسی',
 'بسیار',
 'بسیاری',
 'بشان',
 'بشدت',
 'بشم',
 'بشن',
 'بشه',
 'بشوند',
 'بشی',
 'بشید',
 'بشیم',
 'بشین',
 'بصورت',
 'بطبع',
 'بطور',
 'بطوركلی',
 'بطوري كه',
 'بطوری',
 'بطوری که',
 'بطوریكه',
 'بعد',
 'بعد از اين كه',
 'بعد از این که',
 'بعدا',
 'بعداز',
 'بعدازان',
 'بعدازاین',
 'بعدازظهر',
 'بعداً',
 'بعدها',
 'بعدی',
 'بعری',
 'بعضا',
 'بعضي',
 'بعضي شان',
 'بعضي ها',
 'بعضيهايشان',
 'بعضی',
 'بعضی شان',
 'بعضیشان',
 'بعضیها',
 'بعضیهاشان',
 'بعضیهایشان',
 'بعضی\u200cها',
 'بعلاوه',
 'بعيد',
 'بعید',
 'بفهمي نفهمي',
 'بفهمی',
 'بفهمی نفهمی',
 'بقدری',
 'بكار',
 'بكرات',
 'بلادرنگ',
 'بلافاصله',
 'بلكه',
 'بله',
 'بلکه',
 'بلی',
 'بماند',
 'بمراتب',
 'بموجب',
 'بموقع',
 'بنابراين',
 'بنابراین',
 'بنابرین',
 'بنابه',
 'بناچار',
 'بندرت',
 'بندي',
 'بندی',
 'بنی',
 'به',
 'به آساني',
 'به آسانی',
 'به تازگي',
 'به تازگی',
 'به تدريج',
 'به تدریج',
 'به تمامي',
 'به تمامی',
 'به جاي',
 'به جای',
 'به جز',
 'به خوبي',
 'به خوبی',
 'به درشتي',
 'به درشتی',
 'به دلخواه',
 'به راستي',
 'به راستی',
 'به رغم',
 'به روشني',
 'به روشنی',
 'به زودي',
 'به زودی',
 'به سادگي',
 'به سادگی',
 'به سرعت',
 'به شان',
 'به شدت',
 'به طور',
 'به طور كلي',
 'به طور کلی',
 'به طوري كه',
 'به طوری که',
 'به علاوه',
 'به قدري',
 'به قدری',
 'به كرات',
 'به مراتب',
 'به ناچار',
 'به هرحال',
 'به هيچ وجه',
 'به هیچ وجه',
 'به وضوح',
 'به ويژه',
 'به ویژه',
 'به کرات',
 'به گرمي',
 'به گرمی',
 'بهت',
 'بهتر',
 'بهترين',
 'بهترین',
 'بهتون',
 'بهرحال',
 'بهش',
 'بهشون',
 'بهم',
 'بهیچ',
 'بوجود',
 'بود',
 'بودم',
 'بودن',
 'بودند',
 'بوده',
 'بودی',
 'بودید',
 'بودیم',
 'بوضوح',
 'بويژه',
 'بویژه',
 'بي',
 'بي آنكه',
 'بي اطلاعند',
 'بي ترديد',
 'بي تفاوتند',
 'بي نيازمندانه',
 'بي هدف',
 'بيرون',
 'بيست',
 'بيش',
 'بيشتر',
 'بيشتري',
 'بين',
 'بيگمان',
 'بپا',
 'بکار',
 'بکن',
 'بکند',
 'بکنم',
 'بکنند',
 'بکنی',
 'بکنید',
 'بکنیم',
 'بگذاریم',
 'بگرمی',
 'بگم',
 'بگه',
 'بگو',
 'بگوید',
 'بگویم',
 'بگویند',
 'بگویی',
 'بگویید',
 'بگوییم',
 'بگی',
 'بگیر',
 'بگیرد',
 'بگیرم',
 'بگیرند',
 'بگیری',
 'بگیرید',
 'بگیریم',
 'بگین',
 'بی',
 'بی آنکه',
 'بی اطلاعند',
 'بی تردید',
 'بی تفاوتند',
 'بی نیازمندانه',
 'بی هدف',
 'بیا',
 'بیاب',
 'بیابد',
 'بیابم',
 'بیابند',
 'بیابی',
 'بیابید',
 'بیابیم',
 'بیاد',
 'بیاریم',
 'بیام',
 'بیاور',
 'بیاورد',
 'بیاورم',
 'بیاورند',
 'بیاوری',
 'بیاورید',
 'بیاوریم',
 'بیاید',
 'بیایم',
 'بیایند',
 'بیایی',
 'بیایید',
 'بیاییم',
 'بیرون',
 'بیرونِ',
 'بیست',
 'بیش',
 'بیشتر',
 'بیشتری',
 'بیفته',
 'بین',
 'بینابین',
 'بینمان',
 'بیهوده',
 'بیگمان',
 'ت',
 'تا',
 'تاانجا',
 'تاانجاكه',
 'تاانكه',
 'تااینجا',
 'تااینكه',
 'تابه',
 'تاجاییكه',
 'تاحدودی',
 'تاحدی',
 'تازه',
 'تازگی',
 'تاكنون',
 'تان',
 'تاوقتی',
 'تاوقتیكه',
 'تاکنون',
 'تحت',
 'تحريم هاست',
 'تحریم',
 'تحریم هاست',
 'تحقیق',
 'تدریج',
 'تدریجا',
 'تدریجی',
 'تر',
 'تر  براساس',
 'تر براساس',
 'ترتیب',
 'ترجیحا',
 'تردید',
 'ترند',
 'ترين',
 'تری',
 'تریلیارد',
 'تریلیون',
 'ترین',
 'تصريحاً',
 'تصریحا',
 'تصریحاً',
 'تعداد',
 'تعدادي',
 'تعدادی',
 'تعمدا',
 'تفاوت',
 'تفاوتند',
 'تفننی',
 'تقريبا',
 'تقريباً',
 'تقریبا',
 'تقریباً',
 'تك',
 'تك تك',
 'تلويحاً',
 'تلویحا',
 'تلویحاً',
 'تمام',
 'تمام قد',
 'تماما',
 'تمامشان',
 'تمامي',
 'تمامی',
 'تند',
 'تند تند',
 'تنها',
 'تنهایی',
 'تنگاتنگ',
 'ته',
 'تو',
 'توؤماً',
 'توان',
 'تواند',
 'توانست',
 'توانستم',
 'توانستن',
 'توانستند',
 'توانسته',
 'توانستی',
 'توانستیم',
 'توانم',
 'توانند',
 'توانی',
 'توانید',
 'توانیم',
 'توسط',
 'تولِ',
 'تون',
 'تونست',
 'تووما',
 'توي',
 'توی',
 'تویِ',
 'تویی',
 'تک',
 'تک تک',
 'تی',
 'ث',
 'ثالثا',
 'ثالثاً',
 'ثانياً',
 'ثانی',
 'ثانیا',
 'ثانیاً',
 'ج',
 'جا',
 'جاي',
 'جايي',
 'جای',
 'جایی',
 'جبرگرایانه',
 'جدا',
 'جدااز',
 'جداازهم',
 'جداً',
 'جداگانه',
 'جديد',
 'جديدا',
 'جدی',
 'جدید',
 'جدیدا',
 'جرمزاست',
 'جريان',
 'جریان',
 'جز',
 'جزجز',
 'جسورانه',
 'جلو',
 'جلوتر',
 'جلوي',
 'جلوگيري',
 'جلوگیری',
 'جلوی',
 'جلویری',
 'جلویِ',
 'جمع',
 'جمع اند',
 'جمعا',
 'جمعي',
 'جمعی',
 'جمله',
 'جنابعالي',
 'جنابعالی',
 'جناح',
 'جنس',
 'جنس اند',
 'جهت',
 'جور',
 'جوری',
 'ح',
 'حاشا',
 'حاشاوكلا',
 'حاشيه اي',
 'حاشیه',
 'حاشیه\u200cای',
 'حاضر',
 'حاضرم',
 'حاكيست',
 'حاكیست',
 'حال',
 'حالا',
 'حالكه',
 'حالی',
 'حاکیست',
 'حتما',
 'حتماً',
 'حتي',
 'حتی',
 'حداقل',
 'حداكثر',
 'حداکثر',
 'حدود',
 'حدودا',
 'حدودِ',
 'حرف',
 'حسابگرانه',
 'حسابی',
 'حسب',
 'حضرتعالي',
 'حضرتعالی',
 'حق',
 'حقيرانه',
 'حقیرانه',
 'حقیقتا',
 'حكما',
 'حكماً',
 'حكیمانه',
 'حول',
 'حکماً',
 'خ',
 'خارج',
 'خارجِ',
 'خاست',
 'خالص',
 'خالصانه',
 'خالی',
 'خام',
 'خامسا',
 'خب',
 'خداحافظ',
 'خداروشکر',
 'خداست',
 'خداگونه',
 'خدمات',
 'خردمندانه',
 'خسته',
 'خسته اي',
 'خسته\u200cای',
 'خشمگین',
 'خصمانه',
 'خصوصا',
 'خصوصاً',
 'خلاصه',
 'خلاقانه',
 'خو',
 'خواست',
 'خواستم',
 'خواستن',
 'خواستند',
 'خواسته',
 'خواستی',
 'خواستید',
 'خواستیم',
 'خواه',
 'خواهد',
 'خواهش',
 'خواهم',
 'خواهند',
 'خواهيم',
 ...]

In [38]:
# ! pip install nltk hazm

In [39]:
import nltk
# nltk.download('stopwords')

In [40]:
nltk_stopwords = nltk.corpus.stopwords.words('english')
stopwords.extend(nltk_stopwords)
len(stopwords)

2995

In [41]:
import hazm
stemmer = hazm.Stemmer()

In [42]:
stemmer.stem('کتاب ها')
# ریشه ی کلمه رو برمیگردونه

'کتاب '

In [43]:
from hazm import word_tokenize

word_tokenize('سلام چطور هستی ؟')

['سلام', 'چطور', 'هستی', '؟']

In [44]:
sample_data = data.sample(n=100, random_state=42)
dataset = pd.DataFrame(columns=('title_body', 'category'))
for index, row in sample_data.iterrows():
    title_body = f" {row['Title']} {row['Body']} "
    title_body_tokenized = word_tokenize(title_body)
    title_body_tokenized_filtered = [w for w in title_body_tokenized if not w in stopwords]
    title_body_tokenized_filtered_stemmed = [stemmer.stem(w) for w in title_body_tokenized_filtered]
    dataset.loc[index] = {
        'title_body': ' '.join(title_body_tokenized_filtered_stemmed),
        'category': row['Category2'].replace('\n', '').replace('\u200c', '')
    }

In [45]:
dataset.head()

                                             title_body category
107   پاي چهارمين نشس ‌ ٣ جانبه خط لوله صلح اميدواري...  اجتماعي
5594  خاتمي ديدار سفير ونزوئلا كشور نفت سرمايه نسلي ...    سياسي
6997  استاد ارتباط نياز حياتي غافلي 70 درصد ملزوم صن...     علمي
3984  تعمير بيمارس مصطفي خميني ايل بزودي پاي مي‌رسد ...  بهداشتي
3111  گفت ‌وگو فرش اير بدليل برنامگي داخلي ضربه خورد...  اقتصادي

In [46]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [47]:
vectorizer = TfidfVectorizer()
vectorizer.fit(dataset['title_body'])

TfidfVectorizer()

In [48]:
import pickle
with open('lion_v.jsdh', 'wb') as f:
    pickle.dump(vectorizer, f)

In [49]:
X = vectorizer.transform(dataset['title_body'])

In [50]:
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 12655 stored elements and shape (100, 4954)>

In [51]:
from sklearn.preprocessing import LabelEncoder

In [52]:
le = LabelEncoder()
y = le.fit_transform(dataset['category'])

In [53]:
le.classes_

array(['آموزشي', 'اجتماعي', 'اقتصادي', 'بهداشتي', 'تاريخي', 'سياسي',
       'علمي', 'فرهنگي', 'فقه و حقوق', 'مذهبي', 'ورزشي'], dtype=object)

In [54]:
len(y)

100

In [55]:
import numpy as np
print(np.unique(dataset['category']))

['آموزشي' 'اجتماعي' 'اقتصادي' 'بهداشتي' 'تاريخي' 'سياسي' 'علمي' 'فرهنگي'
 'فقه و حقوق' 'مذهبي' 'ورزشي']

In [56]:
np.shape(X)

(100, 4954)

In [57]:
np.shape(y)

(100,)

In [58]:
from sklearn.model_selection import train_test_split

In [59]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [60]:
from sklearn import svm

In [61]:
svmc = svm.SVC()
svmc.fit(X_train, y_train)

SVC()

In [62]:
svmc.score(X_test, y_test)
# هرچقدر تعداد کلاس ها بره بالا دقت بالا گرفتن سخت تر میشه

0.16

In [63]:
from sklearn.metrics import classification_report, confusion_matrix
y_pred = svmc.predict(X_test)

In [64]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.00      0.00      0.00         1
           2       0.00      0.00      0.00         4
           3       0.00      0.00      0.00         2
           4       0.00      0.00      0.00         2
           5       0.00      0.00      0.00         2
           7       0.00      0.00      0.00         1
           8       0.00      0.00      0.00         5
           9       0.16      1.00      0.28         4
          10       0.00      0.00      0.00         2

    accuracy                           0.16        25
   macro avg       0.02      0.10      0.03        25
weighted avg       0.03      0.16      0.04        25

/home/arian/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/arian/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/arian/anaconda3/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1879: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [65]:
print(confusion_matrix(y_test, y_pred))

[[0 0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 4 0]
 [0 0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 0 2 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 5 0]
 [0 0 0 0 0 0 0 0 4 0]
 [0 0 0 0 0 0 0 0 2 0]]

In [66]:
with open('svmc.h5', 'wb') as f:
    pickle.dump(svmc, f)